#pragma config(Motor,  port2,           lA,            tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port3,           lB,            tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port4,           lC,            tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port5,           rA,            tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port6,           rB,            tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port7,           rC,            tmotorVex393_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#define LIM_TO_VAL(val, lim) ( (abs(val) < lim)? val : lim * sgn(val) )
void setDrive(word l, word r)
{
	motor[lA] = motor[lB] = motor[lC] = LIM_TO_VAL(l, 127);
	motor[rA] = motor[rB] = motor[rC] = LIM_TO_VAL(r, 127);
}


task main()
{
	word throttle, turn;
	while (true)
	{
		throttle = vexRT[Ch2];
		turn = vexRT[Ch1];
		setDrive(throttle+turn, throttle-turn);
		sleep(10);
	}
}
