#pragma config(Motor,  port2,           mtr,           tmotorNone, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	motor[mtr] = 127;
	while(true) sleep(10);
}
