#pragma config(Motor,  port2,           mtr,         tmotorVex393TurboSpeed_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//
#include "../src/task.h"
#include "motors.h"
#include "sensors.h"
#include "joysticks.h"
#include "utilities.h"
#include "auto.h"
#include "cycle.h"

// Year-independent libraries (source)
#include "task.c"
#include "motors.c"
#include "sensors.c"
#include "joysticks.c"
#include "utilities.c"
#include "cycle.c"

task update()
{
	while (true)
	{
		updateMotors();
		sleep(5);
	}
}

task main()
{
	setupMotors();
	startTask(update);
	while (true)
	{
		gMotor[mtr].power = vexRT[ch2];
		sleep(10);
		//writeDebugStreamLine("%d m: %d", npgmtime, motor[mtr]);
	}
	stopTask(update);
}
