#pragma config(Sensor, in3,    sensor,         sensorPotentiometer)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	while (true)
	{
		writeDebugStreamLine("%d | Poti: %d", nPgmTime, SensorValue[sensor]);
		//clearLCDLine(0);
		//displayLCDNumber(0, 0, SensorValue[sensor]);
		//datalogDataGroupStart();
		datalogAddValueWithTimeStamp(0, SensorValue[sensor]);
		//datalogDataGroupEnd();
		sleep(10);
	}
}
