#pragma config(Sensor, dgtl2,  enc,            sensorQuadEncoder)
#pragma config(Motor,  port2,           mtr,           tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           mtrR,          tmotorVex393_MC29, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "../src/task.h"
#include "motors.h"
#include "sensors.h"
#include "joysticks.h"
#include "utilities.h"
#include "auto.h"

// Year-independent libraries (source)
#include "task.c"
#include "motors.c"
#include "sensors.c"
#include "joysticks.c"
#include "utilities.c"

#define GEAR_RATIO 1.0
#define RELOAD_VAL (360.0*GEAR_RATIO)

#define POWER(pwr) motor[mtr] = motor[mtrR] = pwr

//TODO: Make sure that encoder and motor spins forwards
//TODO: Make sure offset & breaking loop is tuned
//TODO: Add puncher reset

task printBttn()
{
	while (true)
	{
		bool button = vexRT[Btn6U];

		datalogDataGroupStart();
		datalogAddValue(1, button);
		datalogDataGroupEnd();

		sleep(10);
	}
}

task main()
{
	clearDebugStream();
	setupSensors();
	setupMotors();
	setupJoysticks();
	tInit();

	gSensor[enc].value = 0;
	const int startVal = gSensor[enc].value;
	int shotCount = 0;

	startTask(autoMotorSensorUpdateTask);
	///startTask(printBttn);

	float offset = 30;
	float breakKp = -15.0;

	bool button, lstButton;
	writeDebugStreamLine("Start");
	while (true)
	{
		button = vexRT[Btn6U];

		if (button && !lstButton)
		{
			unsigned long startTime = npgmtime;
			writeDebugStreamLine("%d button push", npgmtime);
			shotCount++;
			POWER(127);
			float target = shotCount * RELOAD_VAL;
			writeDebugStreamLine("%d Start shot%d %f %d %d %d", npgmtime, shotCount, target, gSensor[enc].value, startVal, offset);
			while( (gSensor[enc].value - startVal) < (target-offset) ) //Spin 1 rotation
			{
				writeDebugStreamLine("%d sC:%d, targ:%f, Sensor:%d", nPgmTime, shotCount, target-offset, gSensor[enc].value-startVal);
				sleep(10);
			}
			POWER(0);
			writeDebugStreamLine("%d Start break %d. Val:%d", npgmtime, shotCount, gSensor[enc].value);

			do //Break
			{
				velocityCheck(enc);
				POWER(breakKp * abs(gSensor[enc].velocity));
			} while((gSensor[enc].value - startVal) < target && gSensor[enc].velocity > 0.02);

			POWER(0);
			unsigned long timeElpsd = npgmtime - startTime;
			writeDebugStreamLine("%d Done Move %d. Val:%d. Time%d", npgmtime, shotCount, gSensor[enc].value, timeElpsd);
		}

		lstButton = button;
		sleep(10);
	}

	tStop(autoMotorSensorUpdateTask);
	//stopTask(printBttn);
}
