#pragma config(Sensor, dgtl2,  enc,            sensorQuadEncoder)
#pragma config(Motor,  port2,           mtr,           tmotorVex393_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//
#define GEAR_RATIO (5/3)
#define RELOAD_VAL 360.0*(5.0/(float)3.0)

task main()
{
	sensorValue[enc] = 0;
	const int startVal = sensorValue[enc];
	int shotCount = 0;

	bool button, lstButton;
	writeDebugStreamLine("start");
	while (true)
	{
		button = vexRT[btn6u];

		if (button && !lstButton)
		{
			writeDebugStreamLine("%d button push", npgmtime);
			motor[mtr] = 127;
			shotCount++;

			float target = shotCount * RELOAD_VAL;
			writeDebugStreamLine("Start loop %f", target);
			while( abs(SensorValue[enc] - startVal) < target )
			{
				sleep(50);
				writeDebugStreamLine("%d sC:%d, targ:%f, Sensor:%d", nPgmTime, shotCount, target, SensorValue[enc]);
			}

			motor[mtr] = 0;
		}

		lstButton = button;

		sleep(10);
	}
}
