#pragma config(Sensor, dgtl2,  enc,            sensorQuadEncoder)
#pragma config(Motor,  port2,           mtr,           tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port3,           mtrR,          tmotorVex393_MC29, openL??oop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#define GEAR_RATIO 1.0
#define RELOAD_VAL 360.0*GEAR_RATIO

task printBttn()
{
	while (true)
	{
		bool button = vexRT[Btn6U];

		datalogDataGroupStart();
		datalogAddValue(1, button);
		datalogDataGroupEnd();

		sleep(10);
	}
}

task main()
{
	startTask(printBttn);

	sensorValue[enc] = 0;
	const int startVal = sensorValue[enc];
	int shotCount = 0;

	bool button, lstButton;
	writeDebugStreamLine("start");
	while (true)
	{
		button = vexRT[Btn6U];

		if (button && !lstButton)
		{
			writeDebugStreamLine("%d button push", npgmtime);
			motor[mtr] = motor[mtrR] = 127;
			shotCount++;

			float target = shotCount * RELOAD_VAL;
			writeDebugStreamLine("Start loop %f", target);
			while( abs(SensorValue[enc] - startVal) < target )
			{
				writeDebugStreamLine("%d sC:%d, targ:%f, Sensor:%d", nPgmTime, shotCount, target, SensorValue[enc]);
				sleep(10);
			}

			motor[mtr] = motor[mtrR] = 0;
		}

		lstButton = button;
		sleep(10);
	}

	stopTask(printBttn);
}
