#pragma config(Sensor, dgtl7,  shooterEnc,     sensorQuadEncoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//
#include "../src/task.h"
#include "motors.h"
#include "sensors.h"
#include "joysticks.h"
#include "utilities.h"
#include "auto.h"

// Year-independent libraries (source)
#include "task.c"
#include "motors.c"
#include "sensors.c"
#include "joysticks.c"
#include "utilities.c"

task updateVals()
{
	writeDebugStreamLine("%d Start update", npgmtime);
	while (true)
	{
		hogCPU();
		updateJoysticks();
		updateMotors();
		updateSensorInputs();
		updateSensorOutputs();
		//writeDebugStreamLine("Update-shooter:%d", gSensor[shooterEnc].value);
		releaseCPU();
		sleep(10);
	}
}

task main()
{
	clearDebugStream();
	setupSensors();
	setupMotors();
	setupJoysticks();
	tInit();

	startTask(updateVals);
	while (true)
	{
		velocityCheck(shooterEnc, 2);
		sSensor& s = gSensor[shooterEnc];

		datalogDataGroupStart();
		datalogAddValue(1, s.velocity * 1000);
		datalogAddValue(2, s.lstVelocity * 1000);
		datalogAddValue(3, s.dataPointArr[s.arrHead].value);
		datalogAddValue(4, s.dataPointArr[s.arrTail].value);
		datalogDataGroupEnd();
		//writeDebugStreamLine("%d, vel:%f, h:(%d, %d), t:(%d, %d)", npgmtime, s.velocity, s.dataPointArr[s.arrHead].value, s.dataPointArr[s.arrHead].timestamp, s.dataPointArr[s.arrTail].value, s.dataPointArr[s.arrHead].timestamp);
		sleep(10);
	}
	stopTask(updateVals);

}
