#pragma config(Motor,  port2,           mtr,         tmotorVex393_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	bool toggle = false;
	bool lstButton;
	while (true)
	{
		if (vexRT[btn6u] && !lstButton)
			toggle = !toggle;

		if (toggle)
			motor[mtr] = 127;
		else
			motor[mtr] = 0;

		lstButton = vexRT[btn6u];
		sleep(50);
	}
}
