#pragma config(Sensor, dgtl1,  trackL,         sensorQuadEncoder)
#pragma config(Sensor, dgtl3,  trackR,         sensorQuadEncoder)
#pragma config(Sensor, dgtl5,  trackB,         sensorQuadEncoder)
#pragma config(Motor,  port3,           driveLP,       tmotorVex393TurboSpeed_MC29, openLoop, reversed)
#pragma config(Motor,  port4,           driveLS,       tmotorVex393TurboSpeed_MC29, openLoop)
#pragma config(Motor,  port7,           driveRP,       tmotorVex393TurboSpeed_MC29, openLoop)
#pragma config(Motor,  port8,           driveRS,       tmotorVex393TurboSpeed_MC29, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

int nBatteryLevel;

#include "../src/task.h"
#include "motors.h"
#include "sensors.h"
#include "joysticks.h"
#include "utilities.h"
#include "auto.h"

// Year-independent libraries (source)
#include "task.c"
#include "motors.c"
#include "sensors.c"
#include "joysticks.c"
#include "utilities.c"

task main()
{
	clearDebugStream();
	setupSensors();
	setupMotors();
	setupJoysticks();
	tInit();

 while (true)
 {
   updateSensorInputs();
   updateSensorOutputs();
   velocityCheck(trackL, 100);

   writeDebugStreamLine("vel: %f, lstVel:%f", gSensor[trackL].velocity, gSensor[trackL].lstVelocity);
   sleep(50);
 }
}
