#pragma config(Sensor, in8,    anglerPoti,     sensorPotentiometer)
#pragma config(Motor,  port3,           angler,        tmotorVex393_MC29, openLoop, reversed)
#pragma config(Sensor, dgtl7,  shooterEnc,     sensorQuadEncoder)
#pragma config(Motor,  port5,           shooterA,      tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port6,           shooterRevSplit, tmotorVex393HighSpeed_MC29, openLoop, reversed)
#pragma config(Sensor, in1,    ballDetector,   sensorLineFollower)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#define ANGLE_FLAT 800
#define ANGLE_MID 1400
#define ANGLE_TOP 1800
#define SHOOTER_RELOAD_VAL (360.0)
#define SHOOTER_RELOAD_HOLD 11
#define SHOOTER_RELOAD_POS 145
const int gPresetAngles[3] = {ANGLE_FLAT,ANGLE_MID,ANGLE_TOP};
int curPos = 0;
int shotCount = 0;
bool cancelled = false;
void setShooter(int shootSpeed)
{
	motor[shooterA]=motor[shooterRevSplit]=shootSpeed;
}
void reloadShooter()
{
	setShooter(127);
	int target = shotCount * SHOOTER_RELOAD_VAL;
	while(SensorValue[shooterEnc]<(target+SHOOTER_RELOAD_POS))
	{
		sleep(10);
	}
	setShooter(SHOOTER_RELOAD_HOLD);
}
task shooterTask()
{
	shotCount = 0;
	SensorValue[shooterEnc]=0;
	bool shotTargReached = false;
	while(true)
	{
		cancelled = false;
		if(vexRT[Btn6U])
		{
			int target = shotCount * SHOOTER_RELOAD_VAL;
			if (SensorValue[shooterEnc] < (target+SHOOTER_RELOAD_POS-10)) //Should only get triggered when shooterShotCount == 0
			{
				reloadShooter();
			}
			while(SensorValue[ballDetector]>1000){sleep(10);}
			while(SensorValue[ballDetector]>=250 & SensorValue[ballDetector]<=252){sleep(10);}
			shotCount++;
			target = shotCount * SHOOTER_RELOAD_VAL;
			setShooter(127);
			while(SensorValue[shooterEnc]<target+SHOOTER_RELOAD_POS & cancelled==false)
			{
				if(SensorValue[ballDetector]>1000)
				{
					shotCount--;
					setShooter(-90);
					sleep(100);
					setShooter(0);
					cancelled = true;
				}
			}
			setShooter(SHOOTER_RELOAD_HOLD);
		}
	}
}
task main()
{
	//if(SensorValue[anglerPoti]<gPresetAngles[0]) curPos = 0;
	//if(SensorValue[anglerPoti]<gPresetAngles[1]) curPos = 1;
	//if(SensorValue[anglerPoti]<gPresetAngles[2]) curPos = 2;
	startTask(shooterTask);
	bool BtnAngleUp, BtnAngleUpLst, BtnAngleDown, BtnAngleDownLst;
	while(true)
	{
		BtnAngleUp = vexRT[Btn5U];
		BtnAngleDown = vexRT[Btn5D];
		if(BtnAngleUp && !BtnAngleUpLst)
		{
			if(curPos!=3)
			{
				while(SensorValue[anglerPoti]<gPresetAngles[curPos+1]-100)
				{
					motor[angler] = 75;
				}
				while(SensorValue[anglerPoti]<gPresetAngles[curPos+1])
				{
					motor[angler] = -15;
				}
				motor[angler] = 0;
				curPos+=1;
			}
		}
		BtnAngleUpLst = BtnAngleUp;
	}
}
