//*!!Code automatically generated by 'ROBOTC' configuration wizard           !!*//

/*-----------------------------------------------------------------------------*/
/*                                                                             */
/*                        Copyright (c) James Pearman                          */
/*                                   2013                                      */
/*                            All Rights Reserved                              */
/*                                                                             */
/*-----------------------------------------------------------------------------*/
/*                                                                             */
/*    Module:     flashFileDemo.c                                              */
/*    Author:     James Pearman                                                */
/*    Created:    7 Jan 2014                                                   */
/*                                                                             */
/*    Revisions:                                                               */
/*                V1.00  8 Jan 2014 - Initial release                          */
/*                                                                             */
/*-----------------------------------------------------------------------------*/
/*                                                                             */
/*    The author is supplying this software for use with the VEX cortex        */
/*    control system. This file can be freely distributed and teams are        */
/*    authorized to freely use this program , however, it is requested that    */
/*    improvements or additions be shared with the Vex community via the vex   */
/*    forum.  Please acknowledge the work of the authors when appropriate.     */
/*    Thanks.                                                                  */
/*                                                                             */
/*    Licensed under the Apache License, Version 2.0 (the "License");          */
/*    you may not use this file except in compliance with the License.         */
/*    You may obtain a copy of the License at                                  */
/*                                                                             */
/*      http://www.apache.org/licenses/LICENSE-2.0                             */
/*                                                                             */
/*    Unless required by applicable law or agreed to in writing, software      */
/*    distributed under the License is distributed on an "AS IS" BASIS,        */
/*    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. */
/*    See the License for the specific language governing permissions and      */
/*    limitations under the License.                                           */
/*                                                                             */
/*    The author can be contacted on the vex forums as jpearman                */
/*    or electronic mail using jbpearman_at_mac_dot_com                        */
/*    Mentor for team 8888 RoboLancers, Pasadena CA.                           */
/*                                                                             */
/*-----------------------------------------------------------------------------*/

#include <FlashLib.h>

int integer = 500;
static char tempData[sizeof(integer)];

unsigned char* data;
int fileLength;

void WaitForKey()
{
    while(nLCDButtons == 0)
        sleep(5);
    while(nLCDButtons != 0)
        sleep(5);
}

task main()
{
	clearDebugStream();
	writeDebugStreamLine("Starting Program...");

	if (RCFS_GetFile( "Angler Positions", &data, &fileLength ) == RCFS_SUCCESS)
	{
		memcpy(&integer, data, sizeof(tempData));
		writeDebugStreamLine("Copied data from file, Integer = %d", integer);
	}
	else
	{
		writeDebugStreamLine("Could not find file");
		memcpy(&tempData, &integer, sizeof(integer));
		if(RCFS_AddFile(tempData, sizeof(integer), "Angler Position") == RCFS_ERROR)
			writeDebugStreamLine("File Write Error");
		else writeDebugStream("Wrote new file");

		RCFS_ReadVTOC();

		RCFS_GetFile("Angler Position", &data, &fileLength)
		int tempInteger;
		memcpy(&tempInteger, data, sizeof(tempData));
		writeDebugStreamLine("File has: %d", tempInteger);
	}
}
