#include "controls.hpp"

bool partner_connected = false;

int BTN_DECAPPER_UP;
int BTN_DECAPPER_DOWN;
int BTN_CHANGE_GAME_SIDE;

/* Shooter */
int BTN_FIELD_FRONT_M;
int BTN_FIELD_FRONT_P;
int BTN_FIELD_PF_BACK_RED;
int BTN_FIELD_PF_BACK_BLUE;

void controls_init() {
  // if (partner.is_connected()) {
  //   partner_connected = true;
  //   BTN_DECAPPER_UP = GET_BTN_INDEX(pros::E_CONTROLLER_DIGITAL_X);
  //   BTN_DECAPPER_DOWN = GET_BTN_INDEX(pros::E_CONTROLLER_DIGITAL_A);
  //
  //   BTN_FIELD_FRONT_M = GET_BTN_INDEX(pros::E_CONTROLLER_DIGITAL_Y);
  //   BTN_FIELD_FRONT_P = GET_BTN_INDEX(pros::E_CONTROLLER_DIGITAL_X);
  //   BTN_FIELD_PF_BACK_RED = GET_BTN_INDEX(pros::E_CONTROLLER_DIGITAL_Y);
  //   BTN_FIELD_PF_BACK_BLUE = GET_BTN_INDEX(pros::E_CONTROLLER_DIGITAL_A);
  //   BTN_CHANGE_GAME_SIDE = GET_BTN_INDEX(pros::E_CONTROLLER_DIGITAL_DOWN);
  // } else {
  //   BTN_DECAPPER_UP = GET_BTN_INDEX(pros::E_CONTROLLER_DIGITAL_UP);
  //   BTN_DECAPPER_DOWN = GET_BTN_INDEX(pros::E_CONTROLLER_DIGITAL_LEFT);
  //
  //   BTN_FIELD_FRONT_M = GET_BTN_INDEX(pros::E_CONTROLLER_DIGITAL_X);
  //   BTN_FIELD_FRONT_P = GET_BTN_INDEX(pros::E_CONTROLLER_DIGITAL_X);
  //   BTN_FIELD_PF_BACK_RED = GET_BTN_INDEX(pros::E_CONTROLLER_DIGITAL_Y);
  //   BTN_FIELD_PF_BACK_BLUE = GET_BTN_INDEX(pros::E_CONTROLLER_DIGITAL_A);
  // }
}
