#pragma config(Sensor, in1,    anglerPoti,     sensorPotentiometer)
#pragma config(Sensor, in2,    decapperPoti,   sensorPotentiometer)
#pragma config(Sensor, in8,    ballDetector,   sensorLineFollower)
#pragma config(Sensor, dgtl1,  trackL,         sensorQuadEncoder)
#pragma config(Sensor, dgtl3,  trackR,         sensorQuadEncoder)
#pragma config(Sensor, dgtl5,  trackB,         sensorQuadEncoder)
#pragma config(Sensor, dgtl7,  shooterEnc,     sensorQuadEncoder)
#pragma config(Sensor, dgtl9,  LED1,           sensorLEDtoVCC)
#pragma config(Motor,  port2,           driveLY,       tmotorVex393TurboSpeed_MC29, openLoop, reversed)
#pragma config(Motor,  port3,           intake,        tmotorVex393TurboSpeed_MC29, openLoop)
#pragma config(Motor,  port4,           driveL,        tmotorVex393TurboSpeed_MC29, openLoop)
#pragma config(Motor,  port5,           shooter,       tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port6,           shooterY,      tmotorVex393HighSpeed_MC29, openLoop, reversed)
#pragma config(Motor,  port7,           driveR,        tmotorVex393TurboSpeed_MC29, openLoop, reversed)
#pragma config(Motor,  port8,           angler,        tmotorVex393TurboSpeed_MC29, openLoop, reversed)
#pragma config(Motor,  port9,           driveRY,       tmotorVex393TurboSpeed_MC29, openLoop)
#pragma config(Motor,  port10,          decapper,      tmotorVex393HighSpeed_HBridge, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "../src/utilities.h" //Include this to use LIM_TO_VAL

/* Decapper Controls */
#define JOY_DECAPPER Ch1

/* Decapper Defines */
#define DECAPPER_BOTTOM_POS 100  //Replace with the actual value you measure
#define DECAPPER_TOP_POS 900 //Replace with the actual value you measure

#define DECAPPER_DZ 10

void setDecapper(word power)
{
	motor[decapper] = LIM_TO_VAL(power, 127);
}

task main()
{
	while (true)
	{
		word power = vexRT[JOY_DECAPPER];

		if(abs(power) > DECAPPER_DZ)
		{
			if (power > 0 && SensorValue[decapperPoti] > DECAPPER_TOP_POS) power = 0;
			else if (power < 0 && SensorValue[decapperPoti] < DECAPPER_BOTTOM_POS) power = 0;
		}
		else power = 0;

		setDecapper(power);

		sleep(10);
	}

}
