#pragma config(Motor,  port2,           driveLY,       tmotorVex393TurboSpeed_MC29, openLoop, reversed)
#pragma config(Motor,  port3,           intake,        tmotorVex393TurboSpeed_MC29, openLoop)
#pragma config(Motor,  port4,           driveL,        tmotorVex393TurboSpeed_MC29, openLoop)
#pragma config(Motor,  port7,           driveR,        tmotorVex393TurboSpeed_MC29, openLoop, reversed)
#pragma config(Motor,  port9,           driveRY,       tmotorVex393TurboSpeed_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#define LIM_TO_VAL(input, val) (abs(input) > (val) ? (val) * sgn(input) : (input))

typedef enum _tSpinDir
{
	spinStop,
	spinUp,
	spinDown,
	spinSlowDown,
	spinSlowUp
} tSpinDir;

task main()
{
	bool buttonUp, lstButtonUp, buttonDown, lstButtonDown, buttonSlowUp, lstButtonSlowUp, buttonSlowDown, lstButtonSlowDown;
	tSpinDir spinDir = spinStop;

	while (true)
	{
		buttonUp = vexRT[Btn6U];
		buttonDown = vexRT[Btn6D];
		buttonSlowUp = vexRT[Btn5U];
		buttonSlowDown = vexRT[Btn5D];


		//writeDebugStreamLine("spindir=%d", spinDir);
		if (buttonUp && !lstButtonUp)
		{
			if (spinDir != spinStop)
				spinDir = spinStop;
			else
				spinDir = spinUp;
		}
		else if (buttonDown && !lstButtonDown)
		{
			if (spinDir != spinStop)
				spinDir = spinStop;
			else
				spinDir = spinDown;
		}
		else if (buttonSlowUp && !lstButtonSlowUp)
		{
			if (spinDir != spinStop)
				spinDir = spinStop;
			else
				spinDir = spinSlowUp;
		}
		else if (buttonSlowDown && !lstButtonSlowDown)
		{
			if (spinDir != spinStop)
				spinDir = spinStop;
			else
				spinDir = spinSlowDown;
		}

		switch (spinDir)
		{
			case spinStop:
				motor[intake] = 0;
				break;
			case spinUp:
				motor[intake] = 60;
				break;
			case spinDown:
				motor[intake] = -60;
				break;
			case spinSlowUp:
				motor[intake] = 15;
				break;
			case spinSlowDown:
				motor[intake] = -15;
				break;

		}

		lstButtonUp = buttonUp;
		lstButtonDown = buttonDown;
		lstButtonSlowUp = buttonSlowUp;
		lstButtonSlowDown = buttonSlowDown;
		sleep(10);
	}
}
