#pragma config(Motor,  port2,           intake,         tmotorVex393_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

typedef enum _tSpinDir
{
	spinStop,
	spinUp,
	spinDown
}tSpinDir;

task main()
{
	bool buttonUP, lstButtonUp, buttonDown, lstButtonDown, buttonStop, lstButtonStop;
	tSpinDir spinDir = spinStop;

	while (true)
	{
		buttonUp = vexRT[btn6u];
		buttonDown = vexRT[btn6d];


		//writeDebugStreamLine("spindir=%d", spinDir);
		if (buttonUp && !lstButtonUp)
		{
			if (spinDir != spinStop)
				spinDir = spinStop;
			else
				spinDir = spinUp;
		}
		if (buttonDown && !lstButtonDown)
		{
			if (spinDir != spinStop)
				spinDir = spinStop;
			else
				spinDir = spinDown;
		}

		switch (spinDir)
		{
			case spinStop:
				motor[intake] = 0;
				break;
			case spinUp:
				motor[intake] = 127;
				break;
			case spinDown:
				motor[intake] = -127;
				break;
		}

		lstButtonUp = buttonUp;
		lstButtonDown = buttonDown;
		sleep(50);
	}
}
