#pragma config(Motor,  port2,           mtr,         tmotorVex393TurboSpeed_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	while (true)
	{
		Motor[mtr] = vexRT[ch2];
		sleep(10);
		//writeDebugStreamLine("%d m: %d", npgmtime, motor[mtr]);
	}
}
