#pragma config(Sensor, in1,    ballDetector,   sensorLineFollower)
#pragma config(Sensor, in8,    anglerPoti,     sensorPotentiometer)
#pragma config(Sensor, dgtl1,  trackL,         sensorQuadEncoder)
#pragma config(Sensor, dgtl3,  trackR,         sensorQuadEncoder)
#pragma config(Sensor, dgtl5,  trackB,         sensorQuadEncoder)
#pragma config(Sensor, dgtl7,  shooterEnc,     sensorQuadEncoder)
#pragma config(Motor,  port2,           intake,        tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port5,           shooterA,      tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port6,           shooterRevSplit, tmotorVex393HighSpeed_MC29, openLoop, reversed)
#pragma config(Motor,  port7,           angler,        tmotorVex393TurboSpeed_MC29, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "../src/task.h"
#include "motors.h"
#include "sensors.h"
#include "joysticks.h"
#include "utilities.h"
#include "auto.h"
#include "cycle.h"

// Year-independent libraries (source)
#include "task.c"
#include "motors.c"
#include "sensors.c"
#include "joysticks.c"
#include "utilities.c"
#include "cycle.c"

#define BTN_SHOOT Btn5U
#define BTN_INTAKE_UP Btn6U
#define BTN_INTAKE_DOWN Btn6D

#define JOY_ANGLER Ch2

//#define LIM_TO_VAL(input, val) (abs(input) > (val) ? (val) * sgn(input) : (input))
#define SHOOTER_GEAR_RATIO 1.0
#define SHOOTER_RELOAD_VAL (360.0*SHOOTER_GEAR_RATIO)
#define SHOOTER_RELOAD_HOLD 11
#define SHOOTER_RELOAD_POS 145

int gShooterPow;
/*
task printEnc()
{
	while (true)
	{
		datalogDataGroupStart();
		datalogAddValue(1, gSensor[shooterEnc].value);
		datalogAddValue(2, gShooterPow);
		datalogDataGroupEnd();

		sleep(10);
	}
}
*/
typedef enum _tSpinDir
{
	spinStop,
	spinUp,
	spinDown
}tSpinDir;

task intakeTask()
{
	bool buttonUP, lstButtonUp, buttonDown, lstButtonDown, buttonStop, lstButtonStop;
	tSpinDir spinDir = spinStop;

	while (true)
	{
		buttonUp = vexRT[BTN_INTAKE_UP];
		buttonDown = vexRT[BTN_INTAKE_DOWN];

		//writeDebugStreamLine("spindir=%d", spinDir);
		if (buttonUp && !lstButtonUp)
		{
			if (spinDir != spinStop)
				spinDir = spinStop;
			else
				spinDir = spinUp;
		}
		if (buttonDown && !lstButtonDown)
		{
			if (spinDir != spinStop)
				spinDir = spinStop;
			else
				spinDir = spinDown;
		}

		switch (spinDir)
		{
			case spinStop:
				motor[intake] = 0;
				break;
			case spinUp:
				motor[intake] = 127;
				break;
			case spinDown:
				motor[intake] = -127;
				break;
		}

		lstButtonUp = buttonUp;
		lstButtonDown = buttonDown;
		sleep(50);
	}
}

int shooterShotCount;

void setShooter(word val)
{
	//gMotor[shooterA].power = gMotor[shooterB].power = LIM_TO_VAL(val, 127);
	gShooterPow = LIM_TO_VAL(val, 127);
	gMotor[shooterA].power = gMotor[shooterRevSplit].power = LIM_TO_VAL(val, 127);
}

void reloadShooter()
{
	setShooter(127);
	writeDebugStreamLine("Setup shot #%d encoder start= %d", shooterShotCount,gSensor[shooterEnc].value);
	int target = shooterShotCount * SHOOTER_RELOAD_VAL;
	unsigned long reloadStartTime = npgmtime;
	while (gSensor[shooterEnc].value < (target + SHOOTER_RELOAD_POS))
	{
		sleep(10);
		//writeDebugStreamLine("Enc: %d", gSensor[shooterEnc].value);
	}
	writeDebugStreamLine("Enc: %d", gSensor[shooterEnc].value);
	writeDebugStreamLine("Reload time = %d", npgmtime-reloadStartTime);
	setShooter(SHOOTER_RELOAD_HOLD);
}

task shooterMonitor()
{
	while (true)
	{
		datalogDataGroupStart();
		//datalogAddValue(1, gSensor[shooterEnc].value);
		//datalogAddValue(2, gSensor[ballDetector].value);
		datalogAddValue(3, gMotor[shooterA].power);
		datalogDataGroupEnd();
		sleep(10);
	}
}

task shooterTask()
{
	//startTask(printEnc);
	clearDebugStream();
	int nBatteryLevel = nImmediateBatteryLevel;
	writeDebugStream("%d Battery: %d", nPgmTime, nBatteryLevel);
	shooterShotCount = 0;
	resetQuadratureEncoder(shooterEnc);

	writeDebugStreamLine("Start");
	const float breakKp = -25.0;
	float shooterBreakOffset = 6;

	bool shotTargReached = false;

	bool cancelledPrint = false;
	while (true)
	{

		if (vexRt[BTN_SHOOT])//RISING(BTN_SHOOT) )
		{


			int target = shooterShotCount * SHOOTER_RELOAD_VAL;
			if (gSensor[shooterEnc].value < (target+SHOOTER_RELOAD_POS-10)) //Should only get triggered when shooterShotCount == 0
			{
				reloadShooter();
				while (!vexRT[BTN_SHOOT]) sleep(10);
			}

			if(gSensor[ballDetector].value > 1000)
			{
				if (!cancelledPrint)
				{
					writeDebugStreamLine("%d No Ball - Shot Cancelled");
					cancelledPrint = true;
				}
			}
			else if(gSensor[ballDetector].value >= 250 & gSensor[ballDetector].value <= 252)
			{
				if (!cancelledPrint)
				{
					writeDebugStreamLine("%d Ball Detector Unplugged - Shot Cancelled");
					cancelledPrint = true;
				}
			}
			else
			{
				cancelledPrint = false;
				unsigned long shotStartTime = npgmtime;
				writeDebugStreamLine("%d Shot Start", npgmtime);
				shooterShotCount++;
				target = shooterShotCount * SHOOTER_RELOAD_VAL;
				setShooter(127);
				writeDebugStreamLine("Fired shot #%d at %d, Tgt: %d, Enc: %d, Err: %d", shooterShotCount, nPgmTime, gSensor[shooterEnc].value, target, target - gSensor[shooterEnc].value);

				shotTargReached = ( gSensor[shooterEnc].value > (target-shooterBreakOffset) );
				while (!shotTargReached && (gSensor[shooterEnc].value < (target-80) || gSensor[shooterEnc].value > (target-15) || gSensor[ballDetector].value < 1000))
				{
					shotTargReached = ( gSensor[shooterEnc].value > (target-shooterBreakOffset) );

					unsigned long timeElpsd = npgmtime-shotStartTime;

					sleep(10);
				}
				if (!shotTargReached)
				{
					writeDebugStreamLine("%d Ball gone: Val:%d, Time: %d Pos:%d, Targ:%d ", npgmtime, gSensor[ballDetector].value, npgmtime-shotStartTime, gSensor[shooterEnc].value, target);
					setShooter(-90);
					sleep(100);
					setShooter(0);
					shooterShotCount--;
					PlayTone(300, 50);
				}
				else
				{
					writeDebugStreamLine("%d Shot done accelerating: Time: %d Pos:%d ", npgmtime, npgmtime-shotStartTime, gSensor[shooterEnc].value);
					setShooter(-22);
					unsigned long startBreakTime = npgmtime;
					while ((npgmtime-startBreakTime) < 80)
					{
						writeDebugStreamLine("%d Break", npgmtime);
						if (gSensor[ballDetector].value > 2000)
						{
							writeDebugStreamLine("	%d Ball hit: Time: %d", npgmtime, npgmtime-shotStartTime);
						}
						sleep(10);
					}
					//sleep(80);
					writeDebugStreamLine("Break done at %d, Enc: %d", nPgmTime, gSensor[shooterEnc].value);
					setShooter(0);
					writeDebugStreamLine("Hold done at %d, Tgt: %d, Enc: %d, Err: %d", nPgmTime, target, gSensor[shooterEnc].value, target - gSensor[shooterEnc].value);
					//writeDebugStreamLine("%dStart break %d, %d", npgmtime, shooterShotCount, gSensor[shooterEnc].value);
					//sleep(50);
					reloadShooter();
					writeDebugStreamLine("%d Total Shot Time:%d", npgmtime, npgmtime-shotStartTime);
				}
			}
		}

		sleep(10);
	}
	//stopTask(printEnc);
}

task intakeAnglerTask()
{
	while (true)
	{
		writeDebugStreamLine("%d, Angler: %d", npgmtime, gSensor[anglerPoti].value);
		//if (RISING(BTN_ANGLER_TEST))
		//{

		//}
		//else
		if (abs(gJoy[JOY_ANGLER].cur) > 10)
		{
			if (gSensor[anglerPoti].value > 510 && gSensor[anglerPoti].value < 3037)
				gMotor[angler].power = gJoy[JOY_ANGLER].cur;
		}
		else
		{
			gMotor[angler].power = 0;
		}
		sleep(10);
	}
}

task updateVals()
{
	writeDebugStreamLine("%d Start update", npgmtime);
	sCycleData cycle;
	initCycle(cycle, 10, "UpdateVals");
	while (true)
	{
		tHog();
		updateJoysticks();
		updateMotors();
		updateSensorInputs();
		updateSensorOutputs();
		//writeDebugStreamLine("Update-shooter:%d", gSensor[shooterEnc].value);
		tRelease();
		endCycle(cycle);
	}
}

task main()
{
	clearDebugStream();
	setupSensors();
	setupMotors();
	setupJoysticks();
	tInit();

	//Setup Joystics
	enableJoystick(BTN_SHOOT);
	enableJoystick(JOY_ANGLER);

	resetQuadratureEncoder(ballDetector);

	startTask(updateVals);

	startTask(intakeAnglerTask);
	startTask(intakeTask);
	startTask(shooterTask);
	startTask(shooterMonitor);
	while(true) sleep(10);
	stopTask(intakeAnglerTask);
	stopTask(shooterTask);
	stopTask(intakeTask);
	stopTask(shooterMonitor);
}
