#pragma config(Sensor, in1,    ballDetector,         sensorLineFollower)
#pragma config(Sensor, dgtl1,  trackL,         sensorQuadEncoder)
#pragma config(Sensor, dgtl3,  trackR,         sensorQuadEncoder)
#pragma config(Sensor, dgtl5,  trackB,         sensorQuadEncoder)
#pragma config(Sensor, dgtl7,  shooterEnc,     sensorQuadEncoder)
#pragma config(Motor,  port2,           intake,         tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port5,           shooterA,      tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port6,           shooterRevSplit, tmotorVex393HighSpeed_MC29, openLoop, reversed)
#pragma config(Motor,  port8,           driveR1,       tmotorVex393TurboSpeed_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//
#include "../src/task.h"
#include "motors.h"
#include "sensors.h"
#include "joysticks.h"
#include "utilities.h"
#include "auto.h"

// Year-independent libraries (source)
#include "task.c"
#include "motors.c"
#include "sensors.c"
#include "joysticks.c"
#include "utilities.c"

//#define LIM_TO_VAL(input, val) (abs(input) > (val) ? (val) * sgn(input) : (input))
#define SHOOTER_GEAR_RATIO 1.0
#define SHOOTER_RELOAD_VAL (360.0*SHOOTER_GEAR_RATIO)
#define SHOOTER_RELOAD_HOLD 11

int gShooterPow;
/*
task printEnc()
{
	while (true)
	{
		datalogDataGroupStart();
		datalogAddValue(1, gSensor[shooterEnc].value);
		datalogAddValue(2, gShooterPow);
		datalogDataGroupEnd();

		sleep(10);
	}
}
*/
typedef enum _tSpinDir
{
	spinStop,
	spinUp,
	spinDown
}tSpinDir;

task intakeTask()
{
	bool buttonUP, lstButtonUp, buttonDown, lstButtonDown, buttonStop, lstButtonStop;
	tSpinDir spinDir = spinStop;

	while (true)
	{
		buttonUp = vexRT[btn6u];
		buttonDown = vexRT[btn6d];

		//writeDebugStreamLine("spindir=%d", spinDir);
		if (buttonUp && !lstButtonUp)
		{
			if (spinDir != spinStop)
				spinDir = spinStop;
			else
				spinDir = spinUp;
		}
		if (buttonDown && !lstButtonDown)
		{
			if (spinDir != spinStop)
				spinDir = spinStop;
			else
				spinDir = spinDown;
		}

		switch (spinDir)
		{
			case spinStop:
				motor[intake] = 0;
				break;
			case spinUp:
				motor[intake] = 127;
				break;
			case spinDown:
				motor[intake] = -127;
				break;
		}

		lstButtonUp = buttonUp;
		lstButtonDown = buttonDown;
		sleep(50);
	}
}

int shooterShotCount;

void setShooter(word val)
{
	//gMotor[shooterA].power = gMotor[shooterB].power = LIM_TO_VAL(val, 127);
	gShooterPow = LIM_TO_VAL(val, 127);
	gMotor[shooterA].power = gMotor[shooterRevSplit].power = LIM_TO_VAL(val, 127);
}

void reloadShooter()
{
	setShooter(127);
	writeDebugStreamLine("Setup shot #%d encoder start= %d", shooterShotCount,gSensor[shooterEnc].value);
	int target = shooterShotCount * SHOOTER_RELOAD_VAL;
	unsigned long reloadStartTime = npgmtime;
	while (gSensor[shooterEnc].value < (target + 145))
	{
		sleep(100);
		writeDebugStreamLine("Enc: %d", gSensor[shooterEnc].value);
	}
	writeDebugStreamLine("Enc: %d", gSensor[shooterEnc].value);
	writeDebugStreamLine("Reload time = %d", npgmtime-reloadStartTime);
	setShooter(11);
}

task shooterTask()
{
	//startTask(printEnc);
	clearDebugStream();
	int nBatteryLevel = nImmediateBatteryLevel;
	writeDebugStream("%d Battery: %d", nPgmTime, nBatteryLevel);
	shooterShotCount = 0;
	gSensor[shooterEnc].value = 0;

	word button, lstButton;
	writeDebugStreamLine("Start");
	const float breakKp = -25.0;
	float shooterBreakOffset = 6;
	while (true)
	{
		button = vexRT[Btn5U];

		if (button && !lstButton)
		{
			int target = shooterShotCount * SHOOTER_RELOAD_VAL;
			if (gSensor[shooterEnc].value < (target+90)) //Should only get triggered when shooterShotCount == 0
			{
				reloadShooter();
				while (!vexRT[Btn5U]) sleep(10);
			}

			if(gSensor[ballDetector].value > 1000)
			{
				writeDebugStreamLine("%d No Ball - Shot Cancelled");
			}
			else if(gSensor[ballDetector].value >= 250 & gSensor[ballDetector].value <= 252)
			{
				writeDebugStreamLine("%d Ball Detector Unplugged - Shot Cancelled");
			}
			else
			{
				shooterShotCount++;
				target = shooterShotCount * SHOOTER_RELOAD_VAL;
				setShooter(127);
				writeDebugStreamLine("Fired shot #%d at %d, Tgt: %d, Enc: %d, Err: %d", shooterShotCount, nPgmTime, gSensor[shooterEnc].value, target, target - gSensor[shooterEnc].value);
				while (gSensor[shooterEnc].value < (target-shooterBreakOffset) &&  gSensor[ballDetector].value < 1000) sleep(10);
				writeDebugStreamLine("Forwards done at %d, Enc: %d", nPgmTime, gSensor[shooterEnc].value);
				setShooter(-22);
				sleep(80);
				writeDebugStreamLine("Break done at %d, Enc: %d", nPgmTime, gSensor[shooterEnc].value);
				setShooter(0);
				writeDebugStreamLine("Hold done at %d, Tgt: %d, Enc: %d, Err: %d", nPgmTime, target, gSensor[shooterEnc].value, target - gSensor[shooterEnc].value);
				//writeDebugStreamLine("%dStart break %d, %d", npgmtime, shooterShotCount, gSensor[shooterEnc].value);
				reloadShooter();
			}
		}
		lstButton = button;

		sleep(10);
	}
	//stopTask(printEnc);
}

task shooterSafety
{
	unsigned long highValStartTime = 0;
	while (true)
	{
		if (abs(gMotor[shooterA].power) >= 110 || abs(gMotor[shooterRevSplit].power) >= 110)
			highValStartTime = npgmtime;
		else
			highValStartTime = 0;

		unsigned long elpsdTime = npgmtime - highValStartTime;
		if (highValStartTime != 0 && elpsdTime > 1200)
		{
			setShooter(0);
			stopTask(shooterTask);
		}
		sleep(10);
	}
}

task updateVals()
{
	writeDebugStreamLine("%d Start update", npgmtime);
	while (true)
	{
		hogCPU();
		updateJoysticks();
		updateMotors();
		updateSensorInputs();
		updateSensorOutputs();
		//writeDebugStreamLine("Update-shooter:%d", gSensor[shooterEnc].value);
		releaseCPU();
		sleep(10);
	}
}

task main()
{
	clearDebugStream();
	setupSensors();
	setupMotors();
	setupJoysticks();
	tInit();

	startTask(updateVals);

	startTask(intakeTask);
	startTask(shooterTask);
	while(true) sleep(10);
	stopTask(shooterTask);
	stopTask(intakeTask);
}
