#pragma config(Sensor, in1,    ballDetector,   sensorLineFollower)
#pragma config(Sensor, in8,    anglerPoti,     sensorPotentiometer)
#pragma config(Sensor, dgtl1,  trackL,         sensorQuadEncoder)
#pragma config(Sensor, dgtl3,  trackR,         sensorQuadEncoder)
#pragma config(Sensor, dgtl5,  trackB,         sensorQuadEncoder)
#pragma config(Sensor, dgtl7,  shooterEnc,     sensorQuadEncoder)
#pragma config(Motor,  port2,           driveLY,       tmotorVex393TurboSpeed_MC29, openLoop, reversed)
#pragma config(Motor,  port3,           intake,        tmotorVex393TurboSpeed_MC29, openLoop)
#pragma config(Motor,  port4,           driveL,        tmotorVex393TurboSpeed_MC29, openLoop)
#pragma config(Motor,  port5,           shooter,       tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port6,           shooterY,      tmotorVex393HighSpeed_MC29, openLoop, reversed)
#pragma config(Motor,  port7,           driveR,        tmotorVex393TurboSpeed_MC29, openLoop, reversed)
#pragma config(Motor,  port8,           angler,        tmotorVex393TurboSpeed_MC29, openLoop, reversed)
#pragma config(Motor,  port9,           driveRY,       tmotorVex393TurboSpeed_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#define LIM_TO_VAL(input, val) (abs(input) > (val) ? (val) * sgn(input) : (input))

/* Shooter Defines */
#define BTN_SHOOT Btn5U
#define BTN_INTAKE_UP Btn6U
#define BTN_INTAKE_DOWN Btn6D

#define JOY_ANGLER Ch2
#define BTN_ANGLER_TEST Btn5D

#define RESET_OFFSET 45 //35
#define SHOOTER_GEAR_RATIO 1.0
#define SHOOTER_RELOAD_HOLD 11
#define SHOOTER_SHOOT_POS ((gShooterShotCount*360.0*SHOOTER_GEAR_RATIO) + RESET_OFFSET)
#define SHOOTER_NEXT_SHOOT_POS (((1+gShooterShotCount)*360.0*SHOOTER_GEAR_RATIO) + RESET_OFFSET)
#define SHOOTER_RELOAD_POS ((SHOOTER_SHOOT_POS) + 145)

#define BD_UNPLUGGED (SensorValue[ballDetector] >= 244 && SensorValue[ballDetector] <= 252)

#define BALL_DETECTED (SensorValue[ballDetector] < 1000 && (!BD_UNPLUGGED))

typedef enum _tShooterState
{
	shooterIdle,
	shooterBreak,
	shooterReload,
	shooterHold,
	shooterShoot,
	shooterReset
} tShooterState;

void setShooter(word val)
{
	motor[shooter] = motor[shooterY] = LIM_TO_VAL(val, 127);
}
tShooterState gShooterState = shooterIdle;
tShooterState gShooterStateLst;
unsigned long gShooterStateTime; //Stores the time the shooter state is changed
int gShooterStateSen;
bool gShooterKilled = false;

int gShooterShotCount = 0;
//bool gShooterTimedOut = false;

void setShooterState (tShooterState state)
{
	if (state != gShooterState)
	{
		gShooterStateLst = gShooterState;
		gShooterState = state;

		gShooterStateTime = npgmtime;
		gShooterStateSen = SensorValue[shooterEnc];
		writeDebugStreamLine("%d Shooter State Set %d, Count:%d, Sen:%d, T:%d", nPgmTime, gShooterState, gShooterShotCount, gShooterStateSen, gShooterStateTime);
	}
}

task shooterStateSet()
{
	writeDebugStreamLine("%d Start Shooter State Machine Task", npgmtime);
	float shooterBreakOffset = 8;

	//SensorValue[shooterEnc] = 0;
	SensorValue[shooterEnc] = 0;

	//sCycleData cycle;
	//initCycle(cycle, 10, "shooter");
	while (true)
	{
		switch (gShooterState)
		{
			case shooterIdle:
				setShooter(0);
				break;
			case shooterBreak:
				setShooter(-90);
				unsigned long timerStart = npgmtime;
				while( (npgmTime-timerStart) < 80 ) sleep(10);
				setShooter(0);
				PlayTone(300, 50);

				setShooterState(shooterReload);
				break;
			case shooterReload:
				setShooter(127);
				int target = SHOOTER_RELOAD_POS;

				while(SensorValue[shooterEnc] < target)
				{
					sleep(10);
				}

				writeDebugStreamLine("%d Reloaded to %d", npgmtime, SensorValue[shooterEnc]);

				setShooterState(shooterHold);
				break;
			case shooterHold:
				setShooter(SHOOTER_RELOAD_HOLD);
				break;
			case shooterShoot:
				unsigned long shotStartTime = npgmtime;
				gShooterShotCount++;
				target = SHOOTER_SHOOT_POS;
				setShooter(127);
				writeDebugStreamLine("%d Start shot %d: Time: %d Pos:%d ", npgmtime, gShooterShotCount, npgmtime-shotStartTime, SensorValue[shooterEnc]);

				bool shotTargReached = ( SensorValue[shooterEnc] > (target-shooterBreakOffset) );

				while(!shotTargReached && (SensorValue[shooterEnc] < (target-65) || SensorValue[shooterEnc] > (target-8) || BALL_DETECTED))
				{
					shotTargReached = ( SensorValue[shooterEnc] > (target-shooterBreakOffset) );

					unsigned long timeElpsd = npgmtime-shotStartTime;

					sleep(10);
				}
				if (!shotTargReached)
				{
					writeDebugStreamLine("%d Ball gone: Val:%d, Time: %d Pos:%d, Targ:%d ", npgmtime, SensorValue[ballDetector], npgmtime-shotStartTime, SensorValue[shooterEnc], target);
					gShooterShotCount--;
					PlayTone(300, 50);

					setShooterState(shooterBreak);
				}
				else
				{
					writeDebugStreamLine("%d Start break: Time: %d Pos:%d ", npgmtime, npgmtime-shotStartTime, SensorValue[shooterEnc]);
					setShooter(-25);
					unsigned long startBreakTime = npgmtime;
					while ((npgmtime-startBreakTime) < 80)
					{
						sleep(10);
					}
					setShooter(0);

					writeDebugStreamLine("%d Shoot Trigger False - shot end", npgmtime);

					setShooterState(shooterReload);
				}
				break;

			case shooterReset:
				setShooter(-18);
				float pos = -1;
				float lstPos = -1;
				float vel = -1;
				unsigned long time = npgmtime;
				unsigned long lstTime = 0;
				sleep(250);
				do
				{
					pos = SensorValue[shooterEnc];
					time = npgmtime;

					vel = (float)(pos-lstPos)/(float)(time-lstTime);
					writeDebugStreamLine("%d Vel: %f", npgmtime, vel);
					lstPos = pos;
					lstTime = time;
					sleep(200);
				} while(vel < -0.001);
				setShooter(0);
				sleep(150);
				writeDEbugStreamLine("%d Reset Shooter from %d", npgmtime, SensorValue[shooterEnc]);
				PlayTone(300, 50);
				SensorValue[shooterEnc] = 0;
				gShooterShotCount = 0;
				sleep(50);

				setShooterState(shooterReload);
				break;
		}
		//endCycle(cycle);
		sleep(10);
	}
}

void shooterSafetySet(tShooterState state)
{
	//hogCPU();
	unsigned long stateElpsdTime = (npgmtime-gShooterStateTime);
	int senChange = SensorValue[shooterEnc]-gShooterStateSen;
		writeDebugStreamLine("	%d Shooter State Safety %d. TO: %d SenChange: %d", npgmtime, stateElpsdTime, gShooterState, senChange);
		stopTask(shooterStateSet);
		startTask(shooterStateSet);
		setShooterState(state);
		//releaseCPU();
}

void killShooter()
{
	if (!gShooterKilled)
	{
			//hogCPU();
			gShooterKilled = true;
			stopTask(shooterStateSet);
			setShooter(0);
			writeDebugStreamLine("	%d KILL SHOOTER TASK - Shooter Enc Not Plugged In. State: %d", npgmtime, gShooterState);
			//releaseCPU();
	}
}

void shooterSafety()
{
	if (!gShooterKilled)
	{
		hogCPU();
		unsigned long stateElpsdTime = (npgmtime-gShooterStateTime);
		int senChange = SensorValue[shooterEnc]-gShooterStateSen;

		if (gShooterState == shooterReset)
		{
			if (stateElpsdTime > 4500) shooterSafetySet(shooterIdle);
			else if (stateElpsdTime > 100 && senChange > 10) killShooter();
		}
		else if (gShooterState == shooterReload)
		{
			if (stateElpsdTime > 500) shooterSafetySet(shooterBreak);
			else if (stateElpsdTime > 150 && senChange < 10) killShooter();
		}
		else if (gShooterState == shooterShoot)
		{
			if (stateElpsdTime > 850) shooterSafetySet(shooterBreak);
			else if (stateElpsdTime > 150 && senChange < 10) killShooter();
		}
		releaseCPU();
	}
}

/* Angler Controls */
#define ANGLER_POTI_BOTTOM 125
#define ANGLER_POTI_TOP 3600

void setAngler(word power)
{
	motor[angler] = LIM_TO_VAL(power, 127);
}

void moveAngler(int target)
{
	if (SensorValue[anglerPoti] < target)
	{
		unsigned long curTime = npgmtime;
		int error = 0;
		int lstError = 0;
		unsigned long time = npgmtime;
		unsigned long lstTime = 0;
		float kP = 0.09;//0.085;
		float kD = 5.5;
		while (SensorValue[anglerPoti] < (target-10) && (npgmtime-curTime) < 1500)
		{
			time = npgmtime;
			error = (target - SensorValue[anglerPoti]);
			float pVal = error * kP;
			float dVal = (((float)(error-lstError)/(float)(time-lstTime)) * kD);
			float power = pVal + dVal;
			setAngler(power);
			writeDEbugStreamLine("%d error:%d, pVal:%f, dVal:%f, pow: %f", npgmtime, error, pVal, dVal, power);

			lstError = error;
			lstTime = time;
			sleep(10);
		}
		setAngler(6);
		writeDEbugStreamLine("	%d Done move to %d. Sen: %d, Err: %d, Took: %d", npgmtime, target, SensorValue[anglerPoti], target-SensorValue[anglerPoti], (npgmtime-curTime));
		sleep(400);
		writeDEbugStreamLine("	%d After rest. Targ %d. Sen: %d, Err: %d, Took: %d", npgmtime, target, SensorValue[anglerPoti], target-SensorValue[anglerPoti], (npgmtime-curTime));
	}
}


/* Driver Control */
task driverControl
{
	bool shootBtn = false;
	bool shootBtnLst = false;

	//int lstShotCount = 0;
	unsigned long lstShotTimer = 0;
	while (true)
	{
		shootBtn = vexRT[BTN_SHOOT];

		if (shootBtn && !shootBtnLst)
		{
			if (SensorValue[shooterEnc] < SHOOTER_RELOAD_POS) setShooterState(shooterReload);
			else if (gShooterShotCount != 0 && SensorValue[shooterEnc] >= (SHOOTER_NEXT_SHOOT_POS)) shooterSafetySet(shooterReset);
			else if (BALL_DETECTED)
			{
				setShooterState(shooterShoot);
				lstShotTimer = npgmtime;
				writeDebugStreamLine("%d FIRST SHOT TRIGGERED. # %d. Angler: %d", npgmtime, gShooterShotCount, SensorValue[anglerPoti]);
				//if ((npgmtime-secondShotTimer) > 900) secondShotTimer = npgmtime;
				//else secondShotTimer = 0;
			}
		}

		if (!shootBtn) lstShotTimer = 0;
		else if (shootBtn && gShooterState == shooterHold && (lstShotTimer != 0 && (nPgmTime-lstShotTimer) < 900))
		{
			setShooterState(shooterShoot);
			lstShotTimer = 0;
			writeDebugStreamLine("%d SECOND SHOT TRIGGERED. # %d", npgmtime, gShooterShotCount);
		}

		//Angler Controls
		if (abs(vexRt[Ch2]) > 20)
		{
			if (vexRT[Ch2] > 0 && SensorValue[anglerPoti] < ANGLER_POTI_TOP) setAngler(vexRT[Ch2]);
			else if (vexRT[Ch2] < 0 && SensorValue[anglerPoti] > ANGLER_POTI_BOTTOM) setAngler(vexRT[Ch2]);
		}
		else
		{
			if(SensorValue[anglerPoti] < 800) motor[angler] = -5;
			else if (SensorValue[anglerPoti] > 800 && SensorValue[anglerPoti] < 1000) setAngler(-10);
			else if (SensorValue[anglerPoti] > 1000 && SensorValue[anglerPoti] < 1500) setAngler(0);
			else if (SensorValue[anglerPoti] > 1500 && SensorValue[anglerPoti] < 2250) setAngler(8);
			else if (SensorValue[anglerPoti] > 2250 && SensorValue[anglerPoti] < 2600) setAngler(10);
			else if (SensorValue[anglerPoti] > 2600 &&	SensorValue[anglerPoti] < 3500) setAngler(5);
		}

		shootBtnLst = shootBtn;
		sleep(10);
	}
}

task main()
{
	clearDebugStream();

	int nBatteryLevel = nImmediateBatteryLevel;
	writeDebugStreamLine("%d Battery: %d", nPgmTime, nBatteryLevel);

	SensorValue[shooterEnc] = 0;
	startTask(shooterStateSet);
	startTask(driverControl);
	setShooterState(shooterReset);
	while (true)
	{
		shooterSafety();
		sleep(10);
	}
	stopTask(shooterStateSet);
	stopTask(driverControl);
}
