#pragma config(Sensor, dgtl1,  trackL,         sensorQuadEncoder)
#pragma config(Sensor, dgtl3,  trackR,         sensorQuadEncoder)
#pragma config(Sensor, dgtl5,  trackB,         sensorQuadEncoder)
#pragma config(Motor,  port3,           driveLP,       tmotorVex393TurboSpeed_MC29, openLoop, reversed)
#pragma config(Motor,  port4,           driveLS,       tmotorVex393TurboSpeed_MC29, openLoop)
#pragma config(Motor,  port7,           driveRP,       tmotorVex393TurboSpeed_MC29, openLoop)
#pragma config(Motor,  port8,           driveRS,       tmotorVex393TurboSpeed_MC29, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

int nBatteryLevel;

//#define FORCE_AUTO 1

#define DATALOG_BATTERY -1

#define CHECK_POTI_JUMPS 1
#define DRIVE_TURN (gJoy[JOY_TURN].cur - gJoy[JOY_TURN].deadzone * sgn(gJoy[JOY_TURN].cur))

//#include "state_test.h"
#include "state.h"
#include "func_to_state.h"

// Year-independent libraries (headers)
#include "task.h"
#include "motors.h"
#include "sensors.h"
#include "joysticks.h"
#include "cycle.h"
#include "utilities.h"
#include "auto.h"

// Year-independent libraries (source)
#include "task.c"
#include "motors.c"
#include "sensors.c"
#include "joysticks.c"
#include "cycle.c"
#include "utilities.c"

// Other includes
#include "Vex_Competition_Includes_Custom.c"
#include "controls.h"

/* Drive Controls */
void setDrive(word left, word right)
{
	//writeDebugStreamLine("%d l:%d, r:%d", npgmtime, left, right);
	gMotor[driveLP].power = gMotor[driveLS].power = LIM_TO_VAL(left, 127);
	gMotor[driveRP].power = gMotor[driveRS].power = LIM_TO_VAL(right, 127);
}

CREATE_MACHINE_3(drive, trackL, Idle, Break, Manual, float, Vel, int, Power);
//#include "driveTest.c"
#include "auto.c"
#include "drive_algs.h"
#include "drive_algs.c"

task driveSet()
{
	driveLogs = 1; // Toggle Logging

	sCycleData cycle;
	initCycle(cycle, 10, "drive");
	while (true)
	{
		switch(driveState)
		{
		case driveIdle: //0:
			{
				driveBlocked = 0;
				setDrive(0,0);

				driveStateCycCount++;
				break;
			}
		case driveBreak: //1:
			{
				driveBlocked = 0;
				float startVelL, startVelR;

				const float velThresh = 0.015;
				velocityCheck(trackL);
				velocityCheck(trackR);
				float left = gSensor[trackL].velocity;
				float right = gSensor[trackR].velocity;
				if (driveStateCycCount == 0)
				{
					startVelL = left;
					startVelR = right;
					LOG(drive)("BreakFirstVel %f, %f", startVelL, startVelR);
				}

				LOG(drive)("L: %f, r: %f", left, right);
				if (( abs(left) < velThresh || sgn(left)!=sgn(startVelL) ) && ( abs(right) < velThresh || sgn(right)!=sgn(startVelR) ) )
				{
					driveStateChange(driveIdle);
				}
				else
				{
					setDrive((abs(left) > velThresh? (LIM_TO_VAL(sgn(left) * -50, 12)) : 0), (abs(right) > velThresh? (LIM_TO_VAL(sgn(right) * -50, 12)) : 0) );
				}
				driveStateCycCount++;

				driveSafetyCheck(driveIdle);
				break;
			}
		case driveManual: //2:
			{
				driveBlocked = 0;
				//float angleToTen = atan2( (gPosition.x - 0), (gPosition.y - 10) );
				setDrive((LIM_TO_VAL((gJoy[JOY_THROTTLE].cur + DRIVE_TURN), 127)), (LIM_TO_VAL((gJoy[JOY_THROTTLE].cur - DRIVE_TURN), 127)));
				driveStateCycCount++;

				LOG(drive)("%d (%f,%f) a:%f", npgmtime, gPosition.x, gPosition.y, gPosition.a);

				break;
			}

			//ADD_FUNC_TO_SWITCH_VOID_4(driveFuncTest, drive, driveBreak, driveIdle)
			ADD_FUNC_TO_SWITCH_VOID_7(followLineVec, drive, driveIdle, driveIdle)
			ADD_FUNC_TO_SWITCH_VOID_6(followLine, drive, driveIdle, driveIdle)
			ADD_FUNC_TO_SWITCH_VOID_6(moveToTargetSimple, drive, driveIdle, driveIdle)
			ADD_FUNC_TO_SWITCH_VOID_12(moveToTarget, drive, driveIdle, driveIdle)
			ADD_FUNC_TO_SWITCH_VOID_12(moveToTargetDis, drive, driveBreak, driveIdle)
			ADD_FUNC_TO_SWITCH_VOID_7(turnToAngleNewAlg, drive, driveBreak, driveIdle)
			ADD_FUNC_TO_SWITCH_VOID_9(turnToTargetNewAlg, drive, driveBreak, driveIdle)
			ADD_FUNC_TO_SWITCH_VOID_7(sweepTurnToTarget, drive, driveBreak, driveIdle)
		}
		endCycle(cycle);
	}
}
void handleDrive()
{
	if (!gJoy[JOY_THROTTLE}.cur && !gJoy[JOY_TURN].cur && driveState == driveManual)
	{
		driveStateChange(driveBreak, false, 150);
	}
	else if(gJoy[JOY_THROTTLE}.cur || gJoy[JOY_TURN].cur)
	{
		driveStateChange(driveManual);
	}
}



void startTasks()
{
	resetPositionFull(gPosition, 0, 0, 0);

	//tStart(autoMotorSensorUpdateTask);

	tStart(driveSet);

}

void stopTasks()
{
	tStop(trackPositionTask);

	//tStop(autoMotorSensorUpdateTask);

	tStop(driveSet);
}

void startup()
{
	clearDebugStream();
	setupSensors();
	setupMotors();
	setupJoysticks();
	tInit();

	//Setup Joysticks & Buttons
	enableJoystick(JOY_THROTTLE);
	enableJoystick(JOY_TURN);
	enableJoystick(BTN_SHOOT);

	gJoy[JOY_THROTTLE].deadzone = 15;
	gJoy[JOY_TURN].deadzone = 15;

}

void disabled()
{
	updateSensorInputs();
	//selectAuto();
	//handleLcd();
}

task autonomous()
{
	tStart(autoMotorSensorUpdateTask);
	startTasks();
	writeDebugStreamLine("%d Start Autonomous, %d", npgmtime, nBatteryLevel);

	sCycleData auto;
	initCycle(auto, 10, "auto");
	while(true)
	{
		endCycle(auto);
	}

	tStop(autoMotorSensorUpdateTask);
	stopTasks();
}

task usercontrol()
{
	sCycleData cycle;
	initCycle(cycle, 10, "usercontrol");

	writeDebugStream("%d Start usercontrol",npgmtime);

	startTasks();

	while (true)
	{
		updateJoysticks();
		updateMotors();
		updateSensorInputs();
		updateSensorOutputs();

		handleDrive();

		//setMobileState();

		endCycle(cycle);
	}
	stopTasks();
}
