#pragma config(Motor,  port1,           capper,        tmotorVex393_HBridge, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	while(1)
	{
		int pow = vexRT[Ch2];
		if( abs(pow)<10 ) pow = 0;
		motor[capper] = pow;
		sleep(10);
	}

}
